name: Deploy Vue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm run build

      - name: Deploy with SSH
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ftp.arifurrahmanrasel.top
          REMOTE_USER: arifurra
          TARGET: /home/arifurra/vue.js.arifurrahmanrasel.top/
          SOURCE: dist/